import { createClient } from '@supabase/supabase-js';
import './style.css';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || '';
const SUPABASE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || '';
const supabase = SUPABASE_URL && SUPABASE_KEY ? createClient(SUPABASE_URL, SUPABASE_KEY) : null;
const app=document.querySelector('#app');
let state={tab:'home',user:null,profile:null,videos:[],news:[],search:'',chatUser:null};

const icon=(s)=>`<span class="ico">${s}</span>`;
function shell(){app.innerHTML=`<header><button class="brand" onclick="go('home')"><span class="logo">W</span> Waxtix</button><div class="head-actions"><button onclick="openAuth()">${state.user?'Account':'Sign in'}</button></div></header><main id="view"></main><nav>${[['home','⌂','Home'],['news','▤','News'],['upload','＋','Upload'],['chat','◌','Chat'],['profile','◯','Profile']].map(x=>`<button class="navbtn ${state.tab===x[0]?'active':''}" onclick="go('${x[0]}')">${icon(x[1])}<small>${x[2]}</small></button>`).join('')}</nav>`;render();}
async function load(){if(!supabase){shell();return;} const {data:{session}}=await supabase.auth.getSession();state.user=session?.user||null; if(state.user){const {data:p}=await supabase.from('profiles').select('*').eq('id',state.user.id).maybeSingle();state.profile=p;} await Promise.all([loadVideos(),loadNews()]);shell();}
async function loadVideos(){if(!supabase)return; const {data}=await supabase.from('videos').select('*,profiles(username,display_name,avatar_url)').order('created_at',{ascending:false});state.videos=data||[];}
async function loadNews(){if(!supabase)return; const {data}=await supabase.from('news').select('*,profiles(username,display_name)').order('created_at',{ascending:false});state.news=data||[];}
function loginGate(action){if(!state.user){openAuth();return;}action();}
function render(){const v=document.querySelector('#view'); if(!v)return; if(state.tab==='home')v.innerHTML=home(); if(state.tab==='news')v.innerHTML=news(); if(state.tab==='upload')v.innerHTML=upload(); if(state.tab==='chat')v.innerHTML=chat(); if(state.tab==='profile')v.innerHTML=profile();}
function home(){let list=state.videos.filter(x=>(x.title||'').toLowerCase().includes(state.search.toLowerCase()));return `<section class="page"><div class="top"><div><h1>For you</h1><p>Short videos up to 60 seconds.</p></div></div><input class="search" placeholder="Search videos..." value="${esc(state.search)}" oninput="state.search=this.value;render()">${list.length?list.map(videoCard).join(''):`<div class="empty">No videos yet.<br><span>Sign in to upload the first one.</span></div>`}</section>`}
function videoCard(x){const url=supabase?.storage.from('videos').getPublicUrl(x.storage_path).data.publicUrl||x.video_url||'';return `<article class="card video"><div class="creator">${avatar(x.profiles?.avatar_url)}<b>${esc(x.profiles?.display_name||x.profiles?.username||'Waxtix user')}</b></div><video src="${esc(url)}" controls playsinline preload="metadata"></video><h3>${esc(x.title||'Untitled video')}</h3><p>${esc(x.description||'')}</p><div class="actions"><button onclick="likeVideo('${x.id}')">♡ Like</button><button onclick="shareVideo('${x.id}')">↗ Share</button><button onclick="commentVideo('${x.id}')">💬 Comment</button><button onclick="downloadVideo('${esc(url)}')">⇩ Download</button></div></article>`}
function news(){return `<section class="page"><div class="top"><div><h1>News</h1><p>Photos and written news.</p></div><button class="primary" onclick="go('upload')">＋ Add</button></div>${state.news.length?state.news.map(n=>`<article class="card news"><div class="creator">${icon('📰')}<b>${esc(n.title)}</b></div><p>${esc(n.body)}</p><small>${new Date(n.created_at).toLocaleString()}</small></article>`).join(''):`<div class="empty">No news yet.</div>`}</section>`}
function upload(){return `<section class="page"><h1>Upload video</h1><p class="muted">Only videos are uploaded here. Maximum duration: 60 seconds.</p>${!state.user?`<div class="notice">You can watch without an account. Sign in to upload.</div>`:`<form id="uploadForm" class="card form" onsubmit="doUpload(event)"><label>Video<input id="videoFile" type="file" accept="video/*" required></label><label>Title<input id="videoTitle" maxlength="120" required></label><label>Description<textarea id="videoDesc" maxlength="500"></textarea></label><button class="primary" type="submit">Upload video</button><div id="uploadMsg"></div></form>`}</section>`}
function chat(){return `<section class="page"><div class="top"><div><h1>Chat</h1><p>Message people you follow or create a status.</p></div></div>${state.user?`<div class="card"><button class="primary" onclick="newStatus()">＋ Add status</button><button onclick="findFriends()">Find friends</button><p class="muted">Your conversations will appear here after Supabase chat data is available.</p></div>`:`<div class="notice">Sign in to use Chat, friends and Status.</div>`}</section>`}
function profile(){return `<section class="page">${state.user?`<div class="profileHero"><div class="biglogo">${avatar(state.profile?.avatar_url,'W')}</div><h1>${esc(state.profile?.display_name||state.user.email||'Waxtix user')}</h1><p>${esc(state.profile?.bio||'')}</p><div class="stats"><span><b>0</b> Followers</span><span><b>0</b> Following</span><span><b>0</b> Viewers</span></div></div><div class="card menu"><button onclick="editProfile()">✎ Edit profile</button><button onclick="alert('Language settings are ready for the next step.')">文 Change language</button><button onclick="alert('Help Center: connect your Supabase project and check the README.')">? Help Center</button><button onclick="accountInfo()">⚙ My account</button><button onclick="signOut()">↪ Sign out</button></div>`:`<div class="profileHero"><div class="biglogo">W</div><h1>Welcome to Waxtix</h1><p>Watch videos and read news without signing in.</p><button class="primary" onclick="openAuth()">Sign in</button></div>`}</section>`}
function openAuth(){document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="auth"><div class="modalbox"><button class="close" onclick="document.querySelector('#auth').remove()">×</button><h2>Sign in to Waxtix</h2><p class="muted">Email, phone OTP, or Google.</p><input id="authEmail" placeholder="Email"><input id="authPass" type="password" placeholder="Password"><button class="primary" onclick="emailAuth()">Sign in / Sign up</button><button onclick="googleAuth()">Continue with Google</button><div class="sep">or phone OTP</div><input id="authPhone" placeholder="+250..." type="tel"><button onclick="phoneOtp()">Send code</button><div id="authMsg"></div></div></div>`)}
async function emailAuth(){if(!supabase)return msg('authMsg','Add Supabase env values first.');const e=val('authEmail'),p=val('authPass');let r=await supabase.auth.signInWithPassword({email:e,password:p});if(r.error){r=await supabase.auth.signUp({email:e,password:p});}if(r.error)return msg('authMsg',r.error.message);document.querySelector('#auth')?.remove();await load();}
async function googleAuth(){if(!supabase)return;const {error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin}});if(error)msg('authMsg',error.message);}
async function phoneOtp(){if(!supabase)return;const {error}=await supabase.auth.signInWithOtp({phone:val('authPhone')});msg('authMsg',error?error.message:'Code sent. Add OTP verification in the next screen.');}
async function signOut(){await supabase?.auth.signOut();state.user=null;state.profile=null;go('home');}
async function doUpload(e){e.preventDefault();const file=document.querySelector('#videoFile').files[0];const m=document.querySelector('#uploadMsg');if(!file)return;if(!state.user)return; if(!file.type.startsWith('video/'))return msgEl(m,'Choose a video file.'); const duration=await getDuration(file);if(duration>60.1)return msgEl(m,'Video is longer than 60 seconds.');msgEl(m,'Uploading...');const path=`${state.user.id}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const {error:up}=await supabase.storage.from('videos').upload(path,file,{contentType:file.type,upsert:false});if(up)return msgEl(m,up.message);const {error}=await supabase.from('videos').insert({user_id:state.user.id,title:val('videoTitle'),description:val('videoDesc'),storage_path:path,duration_seconds:duration});if(error)return msgEl(m,error.message);msgEl(m,'Uploaded successfully.');await loadVideos();go('home');}
function getDuration(file){return new Promise((resolve,reject)=>{const v=document.createElement('video');v.preload='metadata';v.onloadedmetadata=()=>{URL.revokeObjectURL(v.src);resolve(v.duration)};v.onerror=reject;v.src=URL.createObjectURL(file);});}
async function likeVideo(id){if(!state.user)return openAuth();const {error}=await supabase.from('likes').upsert({user_id:state.user.id,video_id:id});if(error)alert(error.message);else alert('Liked.');}
function shareVideo(id){const u=location.href.split('#')[0]+'#video='+id;navigator.share?navigator.share({title:'Waxtix video',url:u}):navigator.clipboard?.writeText(u).then(()=>alert('Link copied.'));}
function commentVideo(){loginGate(()=>alert('Comment box is connected to the comments table in the database; add a comment UI when you want it enabled.'));}
function downloadVideo(url){if(!url)return alert('Video URL unavailable.');const a=document.createElement('a');a.href=url;a.download='waxtix-video';a.target='_blank';a.click();}
function newStatus(){const t=prompt('Write your status');if(!t||!supabase)return;supabase.from('statuses').insert({user_id:state.user.id,text:t}).then(r=>alert(r.error?r.error.message:'Status added.'));}
function findFriends(){alert('Use Chat to search people by username. The database is ready for this feature.');}
function editProfile(){const name=prompt('Display name',state.profile?.display_name||'');if(name===null)return;supabase.from('profiles').update({display_name:name}).eq('id',state.user.id).then(async r=>{if(r.error)alert(r.error.message);else{await load();}})}
function accountInfo(){alert(`Email: ${state.user.email||''}\nPhone: ${state.user.phone||'Not set'}`)}
function go(t){state.tab=t;shell();}
function val(id){return document.getElementById(id)?.value.trim()||''} function msg(id,t){const e=document.getElementById(id);if(e)e.textContent=t;} function msgEl(e,t){e.textContent=t}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));} function avatar(url,f='👤'){return url?`<img class="avatar" src="${esc(url)}">`:`<span class="avatar">${f}</span>`}
Object.assign(window,{go,openAuth,emailAuth,googleAuth,phoneOtp,signOut,doUpload,likeVideo,shareVideo,commentVideo,downloadVideo,newStatus,findFriends,editProfile,accountInfo,state});
supabase?.auth.onAuthStateChange(async()=>{const {data:{session}}=await supabase.auth.getSession();state.user=session?.user||null;if(state.user){const {data:p}=await supabase.from('profiles').select('*').eq('id',state.user.id).maybeSingle();state.profile=p;}shell();});
load();
