create extension if not exists "pgcrypto";
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,username text unique not null,display_name text,avatar_url text,bio text,created_at timestamptz default now());
create table if not exists public.videos(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,title text not null default '',description text,storage_path text not null,duration_seconds numeric not null check(duration_seconds<=60),created_at timestamptz default now());
create table if not exists public.likes(user_id uuid references public.profiles(id) on delete cascade,video_id uuid references public.videos(id) on delete cascade,created_at timestamptz default now(),primary key(user_id,video_id));
create table if not exists public.comments(id uuid primary key default gen_random_uuid(),user_id uuid references public.profiles(id) on delete cascade,video_id uuid references public.videos(id) on delete cascade,body text not null,created_at timestamptz default now());
create table if not exists public.follows(follower_id uuid references public.profiles(id) on delete cascade,following_id uuid references public.profiles(id) on delete cascade,created_at timestamptz default now(),primary key(follower_id,following_id),check(follower_id<>following_id));
create table if not exists public.news(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,title text not null,body text not null,photo_url text,created_at timestamptz default now());
create table if not exists public.groups(id uuid primary key default gen_random_uuid(),owner_id uuid references public.profiles(id) on delete cascade,name text not null,created_at timestamptz default now());
create table if not exists public.group_members(group_id uuid references public.groups(id) on delete cascade,user_id uuid references public.profiles(id) on delete cascade,role text default 'member',created_at timestamptz default now(),primary key(group_id,user_id));
create table if not exists public.messages(id uuid primary key default gen_random_uuid(),sender_id uuid references public.profiles(id) on delete cascade,recipient_id uuid references public.profiles(id) on delete cascade,group_id uuid references public.groups(id) on delete cascade,body text not null,created_at timestamptz default now(),check(group_id is not null or recipient_id is not null));
create table if not exists public.statuses(id uuid primary key default gen_random_uuid(),user_id uuid references public.profiles(id) on delete cascade,text text not null,created_at timestamptz default now(),expires_at timestamptz default now()+interval '24 hours');
create table if not exists public.transactions(id uuid primary key default gen_random_uuid(),user_id uuid references public.profiles(id) on delete cascade,provider text not null,provider_reference text,amount integer not null,currency text default 'USD',type text not null,status text default 'pending',created_at timestamptz default now());

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,username,display_name) values(new.id,coalesce(nullif(split_part(new.email,'@',1),''),'user_'||substr(new.id::text,1,8)),coalesce(new.raw_user_meta_data->>'full_name',split_part(coalesce(new.email,''),'@',1))) on conflict(id) do nothing; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security; alter table public.videos enable row level security; alter table public.likes enable row level security; alter table public.comments enable row level security; alter table public.follows enable row level security; alter table public.news enable row level security; alter table public.groups enable row level security; alter table public.group_members enable row level security; alter table public.messages enable row level security; alter table public.statuses enable row level security; alter table public.transactions enable row level security;
create policy "profiles read" on public.profiles for select using(true); create policy "profiles own update" on public.profiles for update using(auth.uid()=id);
create policy "videos read" on public.videos for select using(true); create policy "videos insert own" on public.videos for insert with check(auth.uid()=user_id); create policy "videos update own" on public.videos for update using(auth.uid()=user_id); create policy "videos delete own" on public.videos for delete using(auth.uid()=user_id);
create policy "likes read" on public.likes for select using(true); create policy "likes insert own" on public.likes for insert with check(auth.uid()=user_id); create policy "likes delete own" on public.likes for delete using(auth.uid()=user_id);
create policy "comments read" on public.comments for select using(true); create policy "comments insert own" on public.comments for insert with check(auth.uid()=user_id); create policy "comments delete own" on public.comments for delete using(auth.uid()=user_id);
create policy "follows read" on public.follows for select using(true); create policy "follows insert own" on public.follows for insert with check(auth.uid()=follower_id); create policy "follows delete own" on public.follows for delete using(auth.uid()=follower_id);
create policy "news read" on public.news for select using(true); create policy "news insert own" on public.news for insert with check(auth.uid()=user_id); create policy "news update own" on public.news for update using(auth.uid()=user_id); create policy "news delete own" on public.news for delete using(auth.uid()=user_id);
create policy "groups read" on public.groups for select using(true); create policy "groups insert own" on public.groups for insert with check(auth.uid()=owner_id); create policy "groups update own" on public.groups for update using(auth.uid()=owner_id);
create policy "members read" on public.group_members for select using(auth.uid()=user_id or exists(select 1 from public.groups g where g.id=group_members.group_id and g.owner_id=auth.uid())); create policy "members insert self" on public.group_members for insert with check(auth.uid()=user_id); create policy "members delete self" on public.group_members for delete using(auth.uid()=user_id);
create policy "messages participants read" on public.messages for select using(auth.uid()=sender_id or auth.uid()=recipient_id or exists(select 1 from public.group_members m where m.group_id=messages.group_id and m.user_id=auth.uid())); create policy "messages insert own" on public.messages for insert with check(auth.uid()=sender_id);
create policy "statuses read" on public.statuses for select using(expires_at>now()); create policy "statuses insert own" on public.statuses for insert with check(auth.uid()=user_id); create policy "statuses delete own" on public.statuses for delete using(auth.uid()=user_id);
create policy "transactions read own" on public.transactions for select using(auth.uid()=user_id);

insert into storage.buckets(id,name,public) values('videos','videos',true) on conflict(id) do update set public=true;
create policy "video storage public read" on storage.objects for select using(bucket_id='videos');
create policy "video storage own upload" on storage.objects for insert with check(bucket_id='videos' and auth.uid()::text=(storage.foldername(name))[1]);
create policy "video storage own update" on storage.objects for update using(bucket_id='videos' and auth.uid()::text=(storage.foldername(name))[1]);
create policy "video storage own delete" on storage.objects for delete using(bucket_id='videos' and auth.uid()::text=(storage.foldername(name))[1]);
